packages:
  - git
  - nginx
  - python3
  - python3-pip
  - libmysqlclient-dev
  - mariadb-server

write_files:
- path: /etc/systemd/system/razornotes_server.service
  permissions: 0644
  owner: root
  content: |
    [Unit]
    Description=Razor notes server
    
    [Install]
    Alias=razornotes

    [Service]
    User=root
    ExecStart=gunicorn -b 0.0.0.0:5000 run:app -c gunicorn_config.py
    ExecStopPost=/usr/bin/docker rm mycloudservice
    WorkingDirectory=/root/razornotes
    Restart=always

runcmd: 
  - |
   whoami
   cd /root
   git clone https://github.com/Charckle/razornotes.git
   cd razornotes
   pip install -r requirements.txt
   systemctl start mariadb

   mysqladmin -u root password 'myreallysecurepassphrase'
   mysql -u root -e "CREATE DATABASE razor_notes;"
   mysql -u root -e "CREATE USER 'razornotes'@'localhost' IDENTIFIED BY ''; GRANT ALL PRIVILEGES ON razor_notes.* TO 'razornotes'@'localhost'; FLUSH PRIVILEGES;"
   systemctl daemon-reload
   systemctl enable --now razornotes_server.service
