Vagrant.configure("2") do |config|
   config.vm.box = "ubuntu/jammy64"
   config.vm.box_version = "20231201.0.0"
 
   config.vm.provider "virtualbox" do |v|
     v.memory = 1024
     v.cpus = 2
   end
 
   config.vm.define "web" do |web|
     web.vm.network "forwarded_port", guest: 80, host: 8083
   end
 
   # Use cloud-init from a file
   config.vm.cloud_init :user_data, content_type: "text/cloud-config", path: "cloud-init.yml"
   
 end
