packages:
  - git
  - nginx
  - python3
  - python3-pip
  - libmysqlclient-dev
  - mariadb-server
  - net-tools

write_files:
- path: /etc/systemd/system/razornotes_server.service
  permissions: 0644
  owner: root
  content: |
    [Unit]
    Description=Razor notes server
    
    [Install]
    Alias=razornotes

    [Service]
    User=vagrant
    ExecStart=gunicorn -b 0.0.0.0:5000 run:app -c gunicorn_config.py
    WorkingDirectory=/home/vagrant/razornotes
    Restart=always
- path: /root/.ssh/github_temp_pub
  permissions: 0600
  owner: root
  content: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
    QyNTUxOQAAACDkD+z2dLq14UBQfytPtky5hOYsilpjFacHN9MUsi5q4AAAAJjOFff8zhX3
    /AAAAAtzc2gtZWQyNTUxOQAAACDkD+z2dLq14UBQfytPtky5hOYsilpjFacHN9MUsi5q4A
    AAAEDTzcbmycc1T3Q+mRGmsuB5cdJCfkPBbD4HJs+ouULrDeQP7PZ0urXhQFB/K0+2TLmE
    5iyKWmMVpwc30xSyLmrgAAAADnZhZ3JhbnRAdWJ1bnR1AQIDBAUGBw==
    -----END OPENSSH PRIVATE KEY-----

runcmd: 
  - |
   whoami
   ssh-keyscan github.com >> /root/.ssh/known_hosts && eval "$(ssh-agent -s)" && ssh-add /root/.ssh/github_temp_pub && git clone git@github.com:Charckle/razornotes_frontend.git
   #eval "$(ssh-agent -s)" && ssh-add /root/.ssh/github_temp_pub

   apt update
   
   apt install -y ca-certificates curl gnupg
   mkdir -p /etc/apt/keyrings
   curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg

   NODE_MAJOR=20
   echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | sudo tee /etc/apt/sources.list.d/nodesource.list
   apt update

   apt install nodejs -y

   #git clone git@github.com:Charckle/razornotes_frontend.git
   cd razornotes_frontend
   npm ci
   npm run build
   cp -fr ./dist/demo/* /var/www/html
  - |
   whoami
   cd /home/vagrant
   git clone https://github.com/Charckle/razornotes.git
   chown vagrant:vagrant razornotes
   cd razornotes
   pip install -r requirements.txt
   systemctl start mariadb

   mysqladmin -u root password 'myreallysecurepassphrase'
   mysql -u root -e "CREATE DATABASE razor_notes;"
   mysql -u root -e "CREATE USER 'razornotes'@'localhost' IDENTIFIED BY ''; GRANT ALL PRIVILEGES ON razor_notes.* TO 'razornotes'@'localhost'; FLUSH PRIVILEGES;"
   systemctl daemon-reload
   systemctl enable --now razornotes_server.service
