Vagrant.configure("2") do |config|
   config.vm.box = "ubuntu/jammy64"
   config.vm.box_version = "20231201.0.0"

   config.vm.provider "virtualbox" do |v|
     v.memory = 1024
     v.cpus = 2
   end

   config.vm.define "web" do |web|
     web.vm.network "forwarded_port", guest: 80, host: 8083
   end

   $script = <<-'SCRIPT'
   whoami
   sudo apt update && sudo apt upgrade -y
   sudo apt install nginx -y
   curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash


   export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
   [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm
   nvm install 20.10.0
   npm -v
   node -v

   git clone https://github.com/Charckle/razornotes_frontend.git
   cd razornotes_frontend
   npm ci
   npm run build --prod
   sudo cp -fr ./dist/demo/* /var/www/html
   SCRIPT

   config.vm.provision "shell", inline: $script, privileged: false

 end
